In [1]:
import numpy as np
import pandas as pd
import datetime as dt # Datetime
import json # library to handle JSON files

#!conda install -c conda-forge geopy --yes
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

#!conda install -c conda-forge folium=0.5.0 --yes
!pip install folium
import folium #import folium # map rendering library

print('Libraries imported.')

Requirement already satisfied: folium in /opt/conda/envs/Python36/lib/python3.6/site-packages (0.10.0)
Requirement already satisfied: requests in /opt/conda/envs/Python36/lib/python3.6/site-packages (from folium) (2.21.0)
Requirement already satisfied: branca>=0.3.0 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from folium) (0.3.1)
Requirement already satisfied: jinja2>=2.9 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from folium) (2.10)
Requirement already satisfied: numpy in /opt/conda/envs/Python36/lib/python3.6/site-packages (from folium) (1.15.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->folium) (2019.9.11)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->folium) (1.24.1)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->folium) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->folium) (3.0.4)
Requirement already satisfied: six in /opt/conda/envs/Python36/lib/python3.6/site-packages (from branca>=0.3.0->folium) (1.12.0)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from jinja2>=2.9->folium) (1.1.0)
Libraries imported.

In [2]:
# The code was removed by Watson Studio for sharing.

,Sl.No,District,Irrigated Area for High Yielding variety of Ragi (in ha),Un-Irrigated Area for High Yielding variety of Ragi (in ha),Total Area for High Yielding variety of Ragi (in ha),Irrigated Area for Local Yielding variety of Ragi (in ha),Un-Irrigated Area for Local Yielding variety of Ragi (in ha),Total Area for Local Yielding variety of Ragi (in ha),Total irrigated Area for Ragi (in ha),Total Un irrigated Area for Ragi (in ha),Total Area for Ragi (in ha)
0,1,Kancheepuram,300,22,322,5,3,8,305,25,330
1,2,Thiruvallur,218,17,235,7,8,15,225,25,250
2,3,Cuddalore,35,124,159,0,0,0,35,124,159
3,4,Villupuram,953,247,1200,10,17,27,963,264,1227
4,5,Vellore,2733,1783,4516,3,0,3,2736,1783,4519

In [3]:
df_data_1.shape

(32, 11)

In [4]:
df=df_data_1

In [5]:
df.head()

,Sl.No,District,Irrigated Area for High Yielding variety of Ragi (in ha),Un-Irrigated Area for High Yielding variety of Ragi (in ha),Total Area for High Yielding variety of Ragi (in ha),Irrigated Area for Local Yielding variety of Ragi (in ha),Un-Irrigated Area for Local Yielding variety of Ragi (in ha),Total Area for Local Yielding variety of Ragi (in ha),Total irrigated Area for Ragi (in ha),Total Un irrigated Area for Ragi (in ha),Total Area for Ragi (in ha)
0,1,Kancheepuram,300,22,322,5,3,8,305,25,330
1,2,Thiruvallur,218,17,235,7,8,15,225,25,250
2,3,Cuddalore,35,124,159,0,0,0,35,124,159
3,4,Villupuram,953,247,1200,10,17,27,963,264,1227
4,5,Vellore,2733,1783,4516,3,0,3,2736,1783,4519

In [6]:
df.shape

(32, 11)

In [7]:
df.columns

Index(['Sl.No', 'District',
       'Irrigated Area for High Yielding variety of Ragi (in ha)',
       'Un-Irrigated Area for High Yielding variety of Ragi (in ha)',
       'Total Area for High Yielding variety of Ragi (in ha)',
       'Irrigated Area for Local Yielding variety of Ragi (in ha)',
       'Un-Irrigated Area for Local Yielding variety of Ragi (in ha)',
       'Total Area for Local Yielding variety of Ragi (in ha)',
       'Total irrigated Area for Ragi (in ha)',
       'Total Un irrigated Area for Ragi (in ha)',
       'Total Area for Ragi (in ha)'],
      dtype='object')

### The objective of the study is to help an small scale businessman to move to the district with high proportion of irrigated area for high yielding variety of ragi and decently equipped with ameneties/facilities and has good connectivity. 
### Hence, initially, the columns 3 and 11 are considered to calculate the proportion of irrigated area for high yielding variety of ragi for each of the districts

In [8]:
df= df_data_1.iloc[:,[1,2,10]]

In [9]:
df.head()

,District,Irrigated Area for High Yielding variety of Ragi (in ha),Total Area for Ragi (in ha)
0,Kancheepuram,300,330
1,Thiruvallur,218,250
2,Cuddalore,35,159
3,Villupuram,953,1227
4,Vellore,2733,4519

In [10]:
df.shape

(32, 3)

### Calculate the proportion as (Irrigated Area for High Yielding variety of Ragi /	Total Area for Ragi )

In [11]:
df['proportion']=df['Irrigated Area for High Yielding variety of Ragi (in ha)']/df['Total Area for Ragi (in ha)']

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [12]:
df.head()

,District,Irrigated Area for High Yielding variety of Ragi (in ha),Total Area for Ragi (in ha),proportion
0,Kancheepuram,300,330,0.909091
1,Thiruvallur,218,250,0.872000
2,Cuddalore,35,159,0.220126
3,Villupuram,953,1227,0.776691
4,Vellore,2733,4519,0.604780

In [13]:
df1=df

In [14]:
df1.head()

,District,Irrigated Area for High Yielding variety of Ragi (in ha),Total Area for Ragi (in ha),proportion
0,Kancheepuram,300,330,0.909091
1,Thiruvallur,218,250,0.872000
2,Cuddalore,35,159,0.220126
3,Villupuram,953,1227,0.776691
4,Vellore,2733,4519,0.604780

In [15]:
df1.shape

(32, 4)

In [16]:
df1=df1.iloc[:,[0,3]]

In [17]:
df1.head()

       District  proportion
0  Kancheepuram    0.909091
1   Thiruvallur    0.872000
2     Cuddalore    0.220126
3    Villupuram    0.776691
4       Vellore    0.604780

In [18]:
df1.shape

(32, 2)

In [19]:
df1.tail()

        District  proportion
27   Tirunelveli    1.000000
28   Thoothukudi    0.000000
29  The Nilgiris         NaN
30   Kanyakumari         NaN
31   State Total    0.183583

In [20]:
df1= df1.replace(np.nan, 0)

In [21]:
df1

           District  proportion
0      Kancheepuram    0.909091
1       Thiruvallur    0.872000
2         Cuddalore    0.220126
3        Villupuram    0.776691
4           Vellore    0.604780
5   Thiruvannamalai    0.808680
6             Salem    0.106943
7          Namakkal    0.009747
8        Dharmapuri    0.149781
9       Krishnagiri    0.110740
10       Coimbatore    0.444444
11        Thiruppur    0.000000
12            Erode    0.025228
13   Tiruchirapalli    0.000000
14            Karur    0.000000
15       Perambalur    0.000000
16         Ariyalur    0.289474
17       Pudukottai    0.894737
18        Thanjavur    1.000000
19       Thiruvarur    0.000000
20     Nagapattinam    0.000000
21          Madurai    0.913043
22            Theni    0.139535
23         Dindigul    0.500000
24   Ramanathapuram    0.171053
25     Virudhunagar    0.216216
26       Sivagangai    0.619048
27      Tirunelveli    1.000000
28      Thoothukudi    0.000000
29     The Nilgiris    0.000000
30      Kanyakumari    0.000000
31      State Total    0.183583

In [22]:
df1.drop(df.index[31], inplace=True)

In [23]:
df1

           District  proportion
0      Kancheepuram    0.909091
1       Thiruvallur    0.872000
2         Cuddalore    0.220126
3        Villupuram    0.776691
4           Vellore    0.604780
5   Thiruvannamalai    0.808680
6             Salem    0.106943
7          Namakkal    0.009747
8        Dharmapuri    0.149781
9       Krishnagiri    0.110740
10       Coimbatore    0.444444
11        Thiruppur    0.000000
12            Erode    0.025228
13   Tiruchirapalli    0.000000
14            Karur    0.000000
15       Perambalur    0.000000
16         Ariyalur    0.289474
17       Pudukottai    0.894737
18        Thanjavur    1.000000
19       Thiruvarur    0.000000
20     Nagapattinam    0.000000
21          Madurai    0.913043
22            Theni    0.139535
23         Dindigul    0.500000
24   Ramanathapuram    0.171053
25     Virudhunagar    0.216216
26       Sivagangai    0.619048
27      Tirunelveli    1.000000
28      Thoothukudi    0.000000
29     The Nilgiris    0.000000
30      Kanyakumari    0.000000

### To filter those districts with proportion of atleast 0.005 of ragi irrigated area

In [24]:
df1 = df1.query("proportion>0.005").reset_index()

In [25]:
df1 = df1.drop(columns=['index'])

In [26]:
df1

           District  proportion
0      Kancheepuram    0.909091
1       Thiruvallur    0.872000
2         Cuddalore    0.220126
3        Villupuram    0.776691
4           Vellore    0.604780
5   Thiruvannamalai    0.808680
6             Salem    0.106943
7          Namakkal    0.009747
8        Dharmapuri    0.149781
9       Krishnagiri    0.110740
10       Coimbatore    0.444444
11            Erode    0.025228
12         Ariyalur    0.289474
13       Pudukottai    0.894737
14        Thanjavur    1.000000
15          Madurai    0.913043
16            Theni    0.139535
17         Dindigul    0.500000
18   Ramanathapuram    0.171053
19     Virudhunagar    0.216216
20       Sivagangai    0.619048
21      Tirunelveli    1.000000

In [27]:
import matplotlib.pyplot as plt
plt.bar(df1['District'], df1['proportion'],width = 0.8, color = ['blue']) 
plt.xticks(rotation='vertical')

([0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21],
 <a list of 22 Text xticklabel objects>)

### To get the location coordinates of all those districts

In [28]:
geolocator = Nominatim(user_agent="district")

In [29]:
df1['District_coordinates']= df1['District'].apply(geolocator.geocode).apply(lambda x: (x.latitude, x.longitude))

In [30]:
df1[['Latitude', 'Longitude']] = df1['District_coordinates'].apply(pd.Series)

In [31]:
df1.drop(columns='District_coordinates')

           District  proportion   Latitude   Longitude
0      Kancheepuram    0.909091  12.637438   80.045914
1       Thiruvallur    0.872000  13.139436   79.907304
2         Cuddalore    0.220126  11.742694   79.750306
3        Villupuram    0.776691  11.939829   79.494564
4           Vellore    0.604780  12.907175   79.130970
5   Thiruvannamalai    0.808680  12.208554   79.037947
6             Salem    0.106943  44.939157 -123.033121
7          Namakkal    0.009747  11.219169   78.167870
8        Dharmapuri    0.149781  12.134799   78.158986
9       Krishnagiri    0.110740  12.513614   78.174025
10       Coimbatore    0.444444  11.001812   76.962842
11            Erode    0.025228  11.330648   77.727652
12         Ariyalur    0.289474  11.135771   79.072320
13       Pudukottai    0.894737  10.375158   78.816734
14        Thanjavur    1.000000  10.786027   79.138150
15          Madurai    0.913043   9.926115   78.114098
16            Theni    0.139535  10.010814   77.481010
17         Dindigul    0.500000  10.365541   77.969585
18   Ramanathapuram    0.171053   9.365235   78.834319
19     Virudhunagar    0.216216   9.582240   77.953683
20       Sivagangai    0.619048   9.950117   78.696000
21      Tirunelveli    1.000000   8.729526   77.685235

In [32]:
df1.sort_values(by=['proportion'], ascending=False)

,District,proportion,District_coordinates,Latitude,Longitude
21,Tirunelveli,1.000000,"(8.7295261, 77.6852354)",8.729526,77.685235
14,Thanjavur,1.000000,"(10.7860267, 79.1381497)",10.786027,79.138150
15,Madurai,0.913043,"(9.9261153, 78.1140983)",9.926115,78.114098
0,Kancheepuram,0.909091,"(12.637438, 80.0459143)",12.637438,80.045914
13,Pudukottai,0.894737,"(10.37515825, 78.8167344011985)",10.375158,78.816734
1,Thiruvallur,0.872000,"(13.1394358, 79.9073038)",13.139436,79.907304
5,Thiruvannamalai,0.808680,"(12.2085543, 79.0379472)",12.208554,79.037947
3,Villupuram,0.776691,"(11.9398285, 79.4945645)",11.939829,79.494564
20,Sivagangai,0.619048,"(9.95011745, 78.6959995986838)",9.950117,78.696000
4,Vellore,0.604780,"(12.9071753, 79.1309695)",12.907175,79.130970
17,Dindigul,0.500000,"(10.3655408, 77.9695854)",10.365541,77.969585
10,Coimbatore,0.444444,"(11.0018115, 76.9628425)",11.001812,76.962842
12,Ariyalur,0.289474,"(11.1357708, 79.0723203)",11.135771,79.072320
2,Cuddalore,0.220126,"(11.74269375, 79.7503064417193)",11.742694,79.750306
19,Virudhunagar,0.216216,"(9.5822396, 77.9536831)",9.582240,77.953683
18,Ramanathapuram,0.171053,"(9.3652354, 78.8343193)",9.365235,78.834319
8,Dharmapuri,0.149781,"(12.1347988, 78.1589864)",12.134799,78.158986
16,Theni,0.139535,"(10.0108143, 77.4810104)",10.010814,77.481010
9,Krishnagiri,0.110740,"(12.5136136, 78.1740251889453)",12.513614,78.174025
6,Salem,0.106943,"(44.9391565, -123.033121)",44.939157,-123.033121
11,Erode,0.025228,"(11.3306483, 77.7276519)",11.330648,77.727652
7,Namakkal,0.009747,"(11.2191692, 78.16787)",11.219169,78.167870

### It is noted from above, that the districts 'Tirunelveli' and 'Thanjavur' has higher proportion of Irrigated Area for High Yielding variety of Ragi. 
### Further, to determine the feasible location for the settlement- ameneties, facilities and the connectivity need to be assessed.

In [33]:
address = 'TamilNadu, India'

geolocator = Nominatim(user_agent='state')
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of TamilNadu State are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of TamilNadu State are 10.9094334, 78.3665347.

In [34]:
# Create map of TamilNadu State and add the markers to the map 
map_TamilNadu = folium.Map(location=[latitude, longitude], zoom_start=7)

for lat, lng, prop, dist in zip(df1['Latitude'], df1['Longitude'], df1['proportion'], df1['District']):
    label = '{}, {}'.format(dist, prop)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_TamilNadu)  
    
map_TamilNadu

In [35]:
CLIENT_ID = 'X4LAZF0SDJ2O5JR53KHXFTANMYFNCX5UPJUH04Y4JETKP01Z' # Foursquare ID
CLIENT_SECRET = 'MIM2VG2QHRW5EPZUS3VVUYI5RTQKJXFQ2GYHETYQ2JXSL00O' # Foursquare Secret
VERSION = '20191008' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: X4LAZF0SDJ2O5JR53KHXFTANMYFNCX5UPJUH04Y4JETKP01Z
CLIENT_SECRET:MIM2VG2QHRW5EPZUS3VVUYI5RTQKJXFQ2GYHETYQ2JXSL00O

In [36]:
def getNearbyVenues(names, latitudes, longitudes, radius=4000, LIMIT=100):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['District', 
                  'District Latitude', 
                  'District Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [37]:
location_venues = getNearbyVenues(names=df1['District'],latitudes=df1['Latitude'],longitudes=df1['Longitude'])

Kancheepuram
Thiruvallur
Cuddalore
Villupuram
Vellore
Thiruvannamalai
Salem
Namakkal
Dharmapuri
Krishnagiri
Coimbatore
Erode
Ariyalur
Pudukottai
Thanjavur
Madurai
Theni
Dindigul
Ramanathapuram
Virudhunagar
Sivagangai
Tirunelveli

In [38]:
location_venues

,District,District Latitude,District Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Thiruvallur,13.139436,79.907304,Thiruvallur Railway Station,13.116644,79.914239,Train Station
1,Thiruvallur,13.139436,79.907304,Sennetta Hotel,13.111584,79.914530,Hotel
2,Thiruvallur,13.139436,79.907304,Kamal Salon,13.111209,79.897965,Cosmetics Shop
3,Thiruvallur,13.139436,79.907304,Putlur Railway Station,13.123250,79.936865,Train Station
4,Thiruvallur,13.139436,79.907304,Hotel Sri Sai Vinayaga,13.109010,79.921330,Hotel
5,Thiruvallur,13.139436,79.907304,Tirupachur,13.139416,79.872124,Historic Site
6,Cuddalore,11.742694,79.750306,A2B Restaurant,11.750600,79.760761,Vegetarian / Vegan Restaurant
7,Cuddalore,11.742694,79.750306,Cuddalore Bus Stand,11.746475,79.755533,Bus Station
8,Cuddalore,11.742694,79.750306,Adayar Ananda Bhavan,11.750629,79.760783,Vegetarian / Vegan Restaurant
9,Cuddalore,11.742694,79.750306,MORE. Super Market,11.761534,79.753802,Department Store
10,Villupuram,11.939829,79.494564,bazaar road,11.941552,79.495530,Flea Market
11,Villupuram,11.939829,79.494564,Vilupuram Railway Station (jn),11.941881,79.499352,Light Rail Station
12,Villupuram,11.939829,79.494564,The Chennai Silks,11.927768,79.482563,Costume Shop
13,Villupuram,11.939829,79.494564,Hotel Annamalai Residency,11.962150,79.497919,Indian Restaurant
14,Vellore,12.907175,79.130970,The Vellore Kitchen,12.931468,79.136195,Indian Restaurant
15,Vellore,12.907175,79.130970,China Town,12.924274,79.136958,Chinese Restaurant
16,Vellore,12.907175,79.130970,Harish Food Zone,12.909526,79.132299,Department Store
17,Vellore,12.907175,79.130970,Hotel River View,12.931435,79.137272,Indian Restaurant
18,Vellore,12.907175,79.130970,GRT Regency: Sameera,12.932045,79.138397,Hotel
19,Vellore,12.907175,79.130970,Curry and Hurry,12.908008,79.132597,Asian Restaurant
20,Vellore,12.907175,79.130970,Vellore Fort,12.933552,79.135491,Historic Site
21,Vellore,12.907175,79.130970,Hotel Darling Residency,12.907610,79.132013,Indian Restaurant
22,Vellore,12.907175,79.130970,Hotel Saravana Bhavan,12.926285,79.140090,Indian Restaurant
23,Vellore,12.907175,79.130970,Ibaco Icecream,12.901599,79.131775,Ice Cream Shop
24,Vellore,12.907175,79.130970,HDFC Bank,12.896151,79.129600,Bank
25,Vellore,12.907175,79.130970,Local Market (General Supplies & Vegetables),12.923627,79.135712,Market
26,Thiruvannamalai,12.208554,79.037947,The Dreaming Tree,12.220404,79.058445,Vegetarian / Vegan Restaurant
27,Thiruvannamalai,12.208554,79.037947,Auro Usha Restaurant,12.223375,79.058721,Indian Restaurant
28,Thiruvannamalai,12.208554,79.037947,Arunachala,12.224146,79.058875,Mountain
29,Thiruvannamalai,12.208554,79.037947,Sh@nti Cafe,12.224663,79.058538,Café
...,...,...,...,...,...,...,...
317,Theni,10.010814,77.481010,Royal Enfield Showroom,10.036120,77.484740,Motorcycle Shop
318,Theni,10.010814,77.481010,New Bus stand Theni,10.035395,77.497551,Bus Station
319,Dindigul,10.365541,77.969585,Venu Biriyani,10.358452,77.970878,Restaurant
320,Dindigul,10.365541,77.969585,Dindigul Thalapakatti Biriyani,10.361731,77.972330,Indian Restaurant
321,Dindigul,10.365541,77.969585,Ponram Restaurant,10.360443,77.976012,Multicuisine Indian Restaurant
322,Dindigul,10.365541,77.969585,Dindigul Railway Station,10.354220,77.986052,Train Station
323,Dindigul,10.365541,77.969585,Rajendhra Uma Complex,10.361501,77.990268,Multiplex
324,Dindigul,10.365541,77.969585,Ponram Food Square,10.384327,77.964688,Multicuisine Indian Restaurant
325,Dindigul,10.365541,77.969585,Dindigul Bus Terminal,10.361029,77.978903,Bus Station
326,Ramanathapuram,9.365235,78.834319,Aishwarya Lakshmi Hotel,9.364434,78.834131,Fast Food Restaurant
327,Ramanathapuram,9.365235,78.834319,Ramanathapuram,9.365606,78.849634,Historic Site
328,Ramanathapuram,9.365235,78.834319,Ramanathapuram bus stand,9.364447,78.835248,Bus Station
329,Ramanathapuram,9.365235,78.834319,Elahi Supermarket,9.365847,78.828368,Shopping Mall
330,Ramanathapuram,9.365235,78.834319,Ramanathapuram Railway Station,9.358959,78.837194,Train Station
331,Ramanathapuram,9.365235,78.834319,Koyamnedu Vegetable Market,9.368844,78.827576,Department Store
332,Ramanathapuram,9.365235,78.834319,Anantham Silks,9.368451,78.826762,Department Store
333,Ramanathapuram,9.365235,78.834319,Hotel Garish Park,9.359394,78.842735,Hotel
334,Ramanathapuram,9.365235,78.834319,Arunachala Restaurant,9.368620,78.845530,Seafood Restaurant
335,Ramanathapuram,9.365235,78.834319,Axis Bank ATM,9.370603,78.807228,ATM
336,Virudhunagar,9.582240,77.953683,Burma Kadai,9.580756,77.953312,Indian Restaurant
337,Virudhunagar,9.582240,77.953683,Hotel Burma Kadai,9.608606,77.956216,Indian Restaurant
338,Virudhunagar,9.582240,77.953683,Prince Family Restaurant,9.583401,77.960399,Indian Restaurant
339,Virudhunagar,9.582240,77.953683,Amirtharaj Theatre,9.590151,77.952864,Movie Theater
340,Virudhunagar,9.582240,77.953683,Virudunagar Railway Station,9.594810,77.957594,Train Station
341,Tirunelveli,8.729526,77.685235,Iruttu Kadai (Halwa Store),8.728097,77.688894,Bakery
342,Tirunelveli,8.729526,77.685235,POTHYS,8.729047,77.688952,Clothing Store
343,Tirunelveli,8.729526,77.685235,Srijanakiram Hotels,8.732123,77.711041,Hotel
344,Tirunelveli,8.729526,77.685235,Sri Janakiram Hotels,8.732319,77.711029,Indian Restaurant
345,Tirunelveli,8.729526,77.685235,Tirunelveli Railway Station,8.731387,77.708440,Train Station
346,Tirunelveli,8.729526,77.685235,Santhi Sweets,8.730971,77.710066,Dessert Shop

In [39]:
location_venues[location_venues['District'].str.contains('Kancheepuram')]

Empty DataFrame
Columns: [District, District Latitude, District Longitude, Venue, Venue Latitude, Venue Longitude, Venue Category]
Index: []

In [40]:
location_venues.groupby('District').count()

,District Latitude,District Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
District,,,,,,
Ariyalur,4,4,4,4,4,4
Coimbatore,100,100,100,100,100,100
Cuddalore,4,4,4,4,4,4
Dharmapuri,4,4,4,4,4,4
Dindigul,7,7,7,7,7,7
Erode,7,7,7,7,7,7
Krishnagiri,3,3,3,3,3,3
Madurai,44,44,44,44,44,44
Namakkal,4,4,4,4,4,4
Pudukottai,7,7,7,7,7,7
Ramanathapuram,10,10,10,10,10,10
Salem,100,100,100,100,100,100
Thanjavur,6,6,6,6,6,6
Theni,9,9,9,9,9,9
Thiruvallur,6,6,6,6,6,6
Thiruvannamalai,5,5,5,5,5,5
Tirunelveli,6,6,6,6,6,6
Vellore,12,12,12,12,12,12
Villupuram,4,4,4,4,4,4
Virudhunagar,5,5,5,5,5,5

In [41]:
# get the List of Unique Categories
print('There are {} uniques categories.'.format(len(location_venues['Venue Category'].unique())))

There are 92 uniques categories.

In [42]:
location_venues.shape

(347, 7)

In [43]:
# one hot encoding
venues_onehot = pd.get_dummies(location_venues[['Venue Category']], prefix="", prefix_sep="")

# add street column back to dataframe
venues_onehot['District'] = location_venues['District'] 

# move street column to the first column
fixed_columns = [venues_onehot.columns[-1]] + list(venues_onehot.columns[:-1])

#fixed_columns
venues_onehot = venues_onehot[fixed_columns]

venues_onehot.head()

,District,ATM,Accessories Store,Airport,American Restaurant,Arcade,Asian Restaurant,BBQ Joint,Bakery,Bank,...,Steakhouse,Sushi Restaurant,Theater,Theme Park Ride / Attraction,Thrift / Vintage Store,Train Station,Travel & Transport,Vegetarian / Vegan Restaurant,Warehouse Store,Women's Store
0,Thiruvallur,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,Thiruvallur,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Thiruvallur,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Thiruvallur,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,Thiruvallur,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
TamilNadu_grouped = venues_onehot.groupby('District').mean().reset_index()
TamilNadu_grouped

,District,ATM,Accessories Store,Airport,American Restaurant,Arcade,Asian Restaurant,BBQ Joint,Bakery,Bank,...,Steakhouse,Sushi Restaurant,Theater,Theme Park Ride / Attraction,Thrift / Vintage Store,Train Station,Travel & Transport,Vegetarian / Vegan Restaurant,Warehouse Store,Women's Store
0,Ariyalur,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00
1,Coimbatore,0.000000,0.01,0.000000,0.00,0.00,0.070000,0.01,0.020000,0.000000,...,0.01,0.00,0.00,0.00,0.00,0.010000,0.01,0.03,0.00,0.01
2,Cuddalore,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0.50,0.00,0.00
3,Dharmapuri,0.000000,0.25,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.250000,0.00,0.00,0.00,0.00
4,Dindigul,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.142857,0.00,0.00,0.00,0.00
5,Erode,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00
6,Krishnagiri,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00
7,Madurai,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.045455,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00
8,Namakkal,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00
9,Pudukottai,0.142857,0.00,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00
10,Ramanathapuram,0.100000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.100000,0.00,0.00,0.00,0.00
11,Salem,0.000000,0.00,0.000000,0.07,0.01,0.000000,0.01,0.020000,0.000000,...,0.01,0.01,0.01,0.01,0.01,0.000000,0.00,0.02,0.02,0.00
12,Thanjavur,0.000000,0.00,0.000000,0.00,0.00,0.166667,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00
13,Theni,0.000000,0.00,0.111111,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00
14,Thiruvallur,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.333333,0.00,0.00,0.00,0.00
15,Thiruvannamalai,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0.20,0.00,0.00
16,Tirunelveli,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.166667,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.166667,0.00,0.00,0.00,0.00
17,Vellore,0.000000,0.00,0.000000,0.00,0.00,0.083333,0.00,0.000000,0.083333,...,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00
18,Villupuram,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00
19,Virudhunagar,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.200000,0.00,0.00,0.00,0.00

In [45]:
TamilNadu_grouped.shape

(20, 93)

In [46]:
# What are the top 5 venues/facilities nearby profitable real estate investments?#

num_top_venues = 5

for hood in TamilNadu_grouped['District']:
    print("----"+hood+"----")
    temp = TamilNadu_grouped[TamilNadu_grouped['District'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Ariyalur----
                     venue  freq
0                 Platform  0.25
1  South Indian Restaurant  0.25
2        Currency Exchange  0.25
3        Indian Restaurant  0.25
4        Korean Restaurant  0.00


----Coimbatore----
               venue  freq
0  Indian Restaurant  0.16
1   Asian Restaurant  0.07
2     Clothing Store  0.07
3          Multiplex  0.05
4        Pizza Place  0.05


----Cuddalore----
                           venue  freq
0  Vegetarian / Vegan Restaurant  0.50
1               Department Store  0.25
2                    Bus Station  0.25
3                            ATM  0.00
4                  Movie Theater  0.00


----Dharmapuri----
                     venue  freq
0        Accessories Store  0.25
1  South Indian Restaurant  0.25
2              Coffee Shop  0.25
3            Train Station  0.25
4  North Indian Restaurant  0.00


----Dindigul----
                            venue  freq
0  Multicuisine Indian Restaurant  0.29
1               Indian Restaurant  0.14
2                      Restaurant  0.14
3                   Train Station  0.14
4                     Bus Station  0.14


----Erode----
               venue  freq
0     Ice Cream Shop  0.29
1         Restaurant  0.14
2     Clothing Store  0.14
3     Farmers Market  0.14
4  Food & Drink Shop  0.14


----Krishnagiri----
                     venue  freq
0        Indian Restaurant  0.67
1                    River  0.33
2                 Mountain  0.00
3  North Indian Restaurant  0.00
4                Nightclub  0.00


----Madurai----
               venue  freq
0  Indian Restaurant  0.30
1              Hotel  0.14
2      Movie Theater  0.09
3               Café  0.07
4     Ice Cream Shop  0.05


----Namakkal----
                     venue  freq
0        Indian Restaurant  0.50
1              Bus Station  0.25
2  South Indian Restaurant  0.25
3              Pizza Place  0.00
4                     Park  0.00


----Pudukottai----
               venue  freq
0      Movie Theater  0.29
1    Motorcycle Shop  0.14
2  Indian Restaurant  0.14
3        Coffee Shop  0.14
4        Bus Station  0.14


----Ramanathapuram----
              venue  freq
0  Department Store   0.2
1               ATM   0.1
2     Shopping Mall   0.1
3             Hotel   0.1
4     Train Station   0.1


----Salem----
                 venue  freq
0          Coffee Shop  0.15
1  American Restaurant  0.07
2          Pizza Place  0.05
3                  Bar  0.05
4   Mexican Restaurant  0.04


----Thanjavur----
              venue  freq
0     Historic Site  0.50
1    Ice Cream Shop  0.17
2  Asian Restaurant  0.17
3            Museum  0.17
4          Mountain  0.00


----Theni----
               venue  freq
0  Indian Restaurant  0.44
1        Bus Station  0.33
2            Airport  0.11
3    Motorcycle Shop  0.11
4                ATM  0.00


----Thiruvallur----
            venue  freq
0           Hotel  0.33
1   Train Station  0.33
2   Historic Site  0.17
3  Cosmetics Shop  0.17
4             ATM  0.00


----Thiruvannamalai----
                           venue  freq
0                       Mountain   0.2
1              Indian Restaurant   0.2
2  Vegetarian / Vegan Restaurant   0.2
3                         Resort   0.2
4                           Café   0.2


----Tirunelveli----
               venue  freq
0  Indian Restaurant  0.17
1              Hotel  0.17
2       Dessert Shop  0.17
3      Train Station  0.17
4             Bakery  0.17


----Vellore----
               venue  freq
0  Indian Restaurant  0.33
1     Ice Cream Shop  0.08
2   Department Store  0.08
3              Hotel  0.08
4   Asian Restaurant  0.08


----Villupuram----
                venue  freq
0   Indian Restaurant  0.25
1         Flea Market  0.25
2        Costume Shop  0.25
3  Light Rail Station  0.25
4                Park  0.00


----Virudhunagar----
                     venue  freq
0        Indian Restaurant   0.6
1            Train Station   0.2
2            Movie Theater   0.2
3          Motorcycle Shop   0.0
4  North Indian Restaurant   0.0

In [47]:
# Define a function to return the most common venues/facilities nearby real estate investments

def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [48]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['District']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

In [49]:
# create a new dataframe
venues_sorted = pd.DataFrame(columns=columns)
venues_sorted['District'] = TamilNadu_grouped['District']

for ind in np.arange(TamilNadu_grouped.shape[0]):
    venues_sorted.iloc[ind, 1:] = return_most_common_venues(TamilNadu_grouped.iloc[ind, :], num_top_venues)

In [50]:
venues_sorted.head()

,District,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Ariyalur,South Indian Restaurant,Platform,Indian Restaurant,Currency Exchange,Farmers Market,Cosmetics Shop,Costume Shop,Cupcake Shop,Department Store,Dessert Shop
1,Coimbatore,Indian Restaurant,Clothing Store,Asian Restaurant,Pizza Place,Ice Cream Shop,Multiplex,Hotel,Fast Food Restaurant,Café,Restaurant
2,Cuddalore,Vegetarian / Vegan Restaurant,Bus Station,Department Store,Women's Store,Farmers Market,Cosmetics Shop,Costume Shop,Cupcake Shop,Currency Exchange,Dessert Shop
3,Dharmapuri,South Indian Restaurant,Accessories Store,Train Station,Coffee Shop,Fast Food Restaurant,Cosmetics Shop,Costume Shop,Cupcake Shop,Currency Exchange,Department Store
4,Dindigul,Multicuisine Indian Restaurant,Train Station,Indian Restaurant,Multiplex,Restaurant,Bus Station,Women's Store,Diner,Costume Shop,Cupcake Shop

In [51]:
venues_sorted.shape

(20, 11)

In [52]:
TamilNadu_grouped.shape

(20, 93)

In [53]:
df1.drop(columns='District_coordinates', inplace=True)

In [54]:
TamilNadu_grouped.head()

,District,ATM,Accessories Store,Airport,American Restaurant,Arcade,Asian Restaurant,BBQ Joint,Bakery,Bank,...,Steakhouse,Sushi Restaurant,Theater,Theme Park Ride / Attraction,Thrift / Vintage Store,Train Station,Travel & Transport,Vegetarian / Vegan Restaurant,Warehouse Store,Women's Store
0,Ariyalur,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.0,0.0,0.0,0.000000,0.00,0.00,0.0,0.00
1,Coimbatore,0.0,0.01,0.0,0.0,0.0,0.07,0.01,0.02,0.0,...,0.01,0.0,0.0,0.0,0.0,0.010000,0.01,0.03,0.0,0.01
2,Cuddalore,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.0,0.0,0.0,0.000000,0.00,0.50,0.0,0.00
3,Dharmapuri,0.0,0.25,0.0,0.0,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.0,0.0,0.0,0.250000,0.00,0.00,0.0,0.00
4,Dindigul,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.0,0.0,0.0,0.142857,0.00,0.00,0.0,0.00

In [55]:
TamilNadu_grouped.shape

(20, 93)

## Clustering

In [56]:
from sklearn.cluster import KMeans
# set number of clusters
kclusters = 5

TamilNadu_grouped_clustering = TamilNadu_grouped.drop('District', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(TamilNadu_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([4, 3, 0, 3, 3, 3, 4, 1, 4, 3], dtype=int32)

In [57]:
# add clustering labels
venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

In [58]:
TamilNadu_merged = df1
merged = pd.merge(TamilNadu_merged, venues_sorted, on='District')
merged.head()# check the last columns!

,District,proportion,Latitude,Longitude,Cluster Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Thiruvallur,0.872000,13.139436,79.907304,3,Hotel,Train Station,Cosmetics Shop,Historic Site,Airport,Fast Food Restaurant,Costume Shop,Cupcake Shop,Currency Exchange,Department Store
1,Cuddalore,0.220126,11.742694,79.750306,0,Vegetarian / Vegan Restaurant,Bus Station,Department Store,Women's Store,Farmers Market,Cosmetics Shop,Costume Shop,Cupcake Shop,Currency Exchange,Dessert Shop
2,Villupuram,0.776691,11.939829,79.494564,1,Costume Shop,Indian Restaurant,Light Rail Station,Flea Market,Women's Store,Fast Food Restaurant,Cupcake Shop,Currency Exchange,Department Store,Dessert Shop
3,Vellore,0.604780,12.907175,79.130970,4,Indian Restaurant,Hotel,Bank,Historic Site,Department Store,Chinese Restaurant,Market,Asian Restaurant,Ice Cream Shop,Fried Chicken Joint
4,Thiruvannamalai,0.808680,12.208554,79.037947,1,Vegetarian / Vegan Restaurant,Indian Restaurant,Café,Resort,Mountain,Women's Store,Electronics Store,Costume Shop,Cupcake Shop,Currency Exchange

In [59]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=7)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(merged['Latitude'], merged['Longitude'], merged['District'], merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

In [60]:
merged.loc[merged['Cluster Labels'] == 0, merged.columns[[0] + list(range(5, merged.shape[1]))]]

,District,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
1,Cuddalore,Vegetarian / Vegan Restaurant,Bus Station,Department Store,Women's Store,Farmers Market,Cosmetics Shop,Costume Shop,Cupcake Shop,Currency Exchange,Dessert Shop

In [61]:
merged.loc[merged['Cluster Labels'] == 1, merged.columns[[0] + list(range(5, merged.shape[1]))]]

,District,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
2,Villupuram,Costume Shop,Indian Restaurant,Light Rail Station,Flea Market,Women's Store,Fast Food Restaurant,Cupcake Shop,Currency Exchange,Department Store,Dessert Shop
4,Thiruvannamalai,Vegetarian / Vegan Restaurant,Indian Restaurant,Café,Resort,Mountain,Women's Store,Electronics Store,Costume Shop,Cupcake Shop,Currency Exchange
14,Madurai,Indian Restaurant,Hotel,Movie Theater,Café,Cupcake Shop,Shopping Mall,Bakery,Ice Cream Shop,Department Store,Restaurant

In [62]:
merged.loc[merged['Cluster Labels'] == 2, merged.columns[[0] + list(range(5, merged.shape[1]))]]

,District,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
13,Thanjavur,Historic Site,Ice Cream Shop,Asian Restaurant,Museum,Fast Food Restaurant,Costume Shop,Cupcake Shop,Currency Exchange,Department Store,Dessert Shop

In [63]:
merged.loc[merged['Cluster Labels'] == 3, merged.columns[[0] + list(range(5, merged.shape[1]))]]

,District,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Thiruvallur,Hotel,Train Station,Cosmetics Shop,Historic Site,Airport,Fast Food Restaurant,Costume Shop,Cupcake Shop,Currency Exchange,Department Store
5,Salem,Coffee Shop,American Restaurant,Bar,Pizza Place,Park,Mexican Restaurant,Brewery,Breakfast Spot,Movie Theater,Pub
7,Dharmapuri,South Indian Restaurant,Accessories Store,Train Station,Coffee Shop,Fast Food Restaurant,Cosmetics Shop,Costume Shop,Cupcake Shop,Currency Exchange,Department Store
9,Coimbatore,Indian Restaurant,Clothing Store,Asian Restaurant,Pizza Place,Ice Cream Shop,Multiplex,Hotel,Fast Food Restaurant,Café,Restaurant
10,Erode,Ice Cream Shop,Pizza Place,Food & Drink Shop,Clothing Store,Restaurant,Farmers Market,Food Court,Fried Chicken Joint,Grocery Store,Cosmetics Shop
12,Pudukottai,Movie Theater,ATM,Bus Station,Indian Restaurant,Motorcycle Shop,Coffee Shop,Asian Restaurant,Cupcake Shop,Department Store,Dessert Shop
16,Dindigul,Multicuisine Indian Restaurant,Train Station,Indian Restaurant,Multiplex,Restaurant,Bus Station,Women's Store,Diner,Costume Shop,Cupcake Shop
17,Ramanathapuram,Department Store,Hotel,Shopping Mall,Bus Station,Fast Food Restaurant,Historic Site,Seafood Restaurant,ATM,Train Station,Sushi Restaurant
19,Tirunelveli,Hotel,Indian Restaurant,Train Station,Clothing Store,Bakery,Dessert Shop,Fast Food Restaurant,Costume Shop,Cupcake Shop,Currency Exchange

In [64]:
merged.loc[merged['Cluster Labels'] == 4, merged.columns[[0] + list(range(5, merged.shape[1]))]]

,District,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
3,Vellore,Indian Restaurant,Hotel,Bank,Historic Site,Department Store,Chinese Restaurant,Market,Asian Restaurant,Ice Cream Shop,Fried Chicken Joint
6,Namakkal,Indian Restaurant,South Indian Restaurant,Bus Station,Fast Food Restaurant,Costume Shop,Cupcake Shop,Currency Exchange,Department Store,Dessert Shop,Diner
8,Krishnagiri,Indian Restaurant,River,Women's Store,Farmers Market,Cosmetics Shop,Costume Shop,Cupcake Shop,Currency Exchange,Department Store,Dessert Shop
11,Ariyalur,South Indian Restaurant,Platform,Indian Restaurant,Currency Exchange,Farmers Market,Cosmetics Shop,Costume Shop,Cupcake Shop,Department Store,Dessert Shop
15,Theni,Indian Restaurant,Bus Station,Airport,Motorcycle Shop,Women's Store,Fast Food Restaurant,Cupcake Shop,Currency Exchange,Department Store,Dessert Shop
18,Virudhunagar,Indian Restaurant,Train Station,Movie Theater,Women's Store,Farmers Market,Cosmetics Shop,Costume Shop,Cupcake Shop,Currency Exchange,Department Store

In [65]:
TamilNadu_merged.shape

(22, 4)

In [66]:
venues_sorted.shape

(20, 12)

In [67]:
TamilNadu_merged

           District  proportion   Latitude   Longitude
0      Kancheepuram    0.909091  12.637438   80.045914
1       Thiruvallur    0.872000  13.139436   79.907304
2         Cuddalore    0.220126  11.742694   79.750306
3        Villupuram    0.776691  11.939829   79.494564
4           Vellore    0.604780  12.907175   79.130970
5   Thiruvannamalai    0.808680  12.208554   79.037947
6             Salem    0.106943  44.939157 -123.033121
7          Namakkal    0.009747  11.219169   78.167870
8        Dharmapuri    0.149781  12.134799   78.158986
9       Krishnagiri    0.110740  12.513614   78.174025
10       Coimbatore    0.444444  11.001812   76.962842
11            Erode    0.025228  11.330648   77.727652
12         Ariyalur    0.289474  11.135771   79.072320
13       Pudukottai    0.894737  10.375158   78.816734
14        Thanjavur    1.000000  10.786027   79.138150
15          Madurai    0.913043   9.926115   78.114098
16            Theni    0.139535  10.010814   77.481010
17         Dindigul    0.500000  10.365541   77.969585
18   Ramanathapuram    0.171053   9.365235   78.834319
19     Virudhunagar    0.216216   9.582240   77.953683
20       Sivagangai    0.619048   9.950117   78.696000
21      Tirunelveli    1.000000   8.729526   77.685235

In [68]:
venues_sorted

,Cluster Labels,District,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,4,Ariyalur,South Indian Restaurant,Platform,Indian Restaurant,Currency Exchange,Farmers Market,Cosmetics Shop,Costume Shop,Cupcake Shop,Department Store,Dessert Shop
1,3,Coimbatore,Indian Restaurant,Clothing Store,Asian Restaurant,Pizza Place,Ice Cream Shop,Multiplex,Hotel,Fast Food Restaurant,Café,Restaurant
2,0,Cuddalore,Vegetarian / Vegan Restaurant,Bus Station,Department Store,Women's Store,Farmers Market,Cosmetics Shop,Costume Shop,Cupcake Shop,Currency Exchange,Dessert Shop
3,3,Dharmapuri,South Indian Restaurant,Accessories Store,Train Station,Coffee Shop,Fast Food Restaurant,Cosmetics Shop,Costume Shop,Cupcake Shop,Currency Exchange,Department Store
4,3,Dindigul,Multicuisine Indian Restaurant,Train Station,Indian Restaurant,Multiplex,Restaurant,Bus Station,Women's Store,Diner,Costume Shop,Cupcake Shop
5,3,Erode,Ice Cream Shop,Pizza Place,Food & Drink Shop,Clothing Store,Restaurant,Farmers Market,Food Court,Fried Chicken Joint,Grocery Store,Cosmetics Shop
6,4,Krishnagiri,Indian Restaurant,River,Women's Store,Farmers Market,Cosmetics Shop,Costume Shop,Cupcake Shop,Currency Exchange,Department Store,Dessert Shop
7,1,Madurai,Indian Restaurant,Hotel,Movie Theater,Café,Cupcake Shop,Shopping Mall,Bakery,Ice Cream Shop,Department Store,Restaurant
8,4,Namakkal,Indian Restaurant,South Indian Restaurant,Bus Station,Fast Food Restaurant,Costume Shop,Cupcake Shop,Currency Exchange,Department Store,Dessert Shop,Diner
9,3,Pudukottai,Movie Theater,ATM,Bus Station,Indian Restaurant,Motorcycle Shop,Coffee Shop,Asian Restaurant,Cupcake Shop,Department Store,Dessert Shop
10,3,Ramanathapuram,Department Store,Hotel,Shopping Mall,Bus Station,Fast Food Restaurant,Historic Site,Seafood Restaurant,ATM,Train Station,Sushi Restaurant
11,3,Salem,Coffee Shop,American Restaurant,Bar,Pizza Place,Park,Mexican Restaurant,Brewery,Breakfast Spot,Movie Theater,Pub
12,2,Thanjavur,Historic Site,Ice Cream Shop,Asian Restaurant,Museum,Fast Food Restaurant,Costume Shop,Cupcake Shop,Currency Exchange,Department Store,Dessert Shop
13,4,Theni,Indian Restaurant,Bus Station,Airport,Motorcycle Shop,Women's Store,Fast Food Restaurant,Cupcake Shop,Currency Exchange,Department Store,Dessert Shop
14,3,Thiruvallur,Hotel,Train Station,Cosmetics Shop,Historic Site,Airport,Fast Food Restaurant,Costume Shop,Cupcake Shop,Currency Exchange,Department Store
15,1,Thiruvannamalai,Vegetarian / Vegan Restaurant,Indian Restaurant,Café,Resort,Mountain,Women's Store,Electronics Store,Costume Shop,Cupcake Shop,Currency Exchange
16,3,Tirunelveli,Hotel,Indian Restaurant,Train Station,Clothing Store,Bakery,Dessert Shop,Fast Food Restaurant,Costume Shop,Cupcake Shop,Currency Exchange
17,4,Vellore,Indian Restaurant,Hotel,Bank,Historic Site,Department Store,Chinese Restaurant,Market,Asian Restaurant,Ice Cream Shop,Fried Chicken Joint
18,1,Villupuram,Costume Shop,Indian Restaurant,Light Rail Station,Flea Market,Women's Store,Fast Food Restaurant,Cupcake Shop,Currency Exchange,Department Store,Dessert Shop
19,4,Virudhunagar,Indian Restaurant,Train Station,Movie Theater,Women's Store,Farmers Market,Cosmetics Shop,Costume Shop,Cupcake Shop,Currency Exchange,Department Store

In [69]:
TamilNadu_merged[~TamilNadu_merged.District.isin(venues_sorted.District)]

        District  proportion   Latitude  Longitude
0   Kancheepuram    0.909091  12.637438  80.045914
20    Sivagangai    0.619048   9.950117  78.696000